# Generated by Django 5.1.6 on 2025-03-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_handle', models.URLField()),
            ],
        ),
    ]
