# Generated by Django 5.1.6 on 2025-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_downbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veggie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('todo', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=50)),
            ],
        ),
    ]
