# Generated by Django 5.1.6 on 2025-03-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_logistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veggie',
        ),
    ]
