# Generated by Django 5.1.6 on 2025-03-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_vegie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.CharField(max_length=200)),
                ('image_testimony', models.ImageField(upload_to='img/')),
                ('testimony_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
    ]
